greeting:
  message: "hello"

quarkus:
  datasource:
    db-kind: postgresql
    username: postgres
    password: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/Travelhub_db

  flyway:
    migrate-at-start: true
    baseline-on-migrate: true

  hibernate-orm:
    database:
      generation: none
    log:
      sql: true

  oidc:
    auth-server-url: http://localhost:8081/realms/travelhub
    client-id: travelhub-backend
    application-type: service
    tls:
      verification: none
    credentials:
      secret: ${KEYCLOAK_CLIENT_SECRET}
  http:
    auth:
      permission:
        authenticated:
          paths: /api/*
          policy: authenticated

  keycloak:
    devservices:
      enabled: false
    admin:
      server-url: http://localhost:8081
      realm: travelhub